# Site settings
title: WPE WebKit
subtitle: A WebKit port optimized for embedded devices
email: webkit-wpe@lists.webkit.org
description: >
  WPE WebKit allows embedders to create simple and performant systems
  based on Web platform technologies.
  It is designed with hardware acceleration in mind,
  leveraging common 3D graphics APIs for best performance.
baseurl: ""
url: "https://wpewebkit.org"
twitter_username: WPEWebKit
exclude: ['README.md', 'generate-site', 'releases', 'webkit-release', 'generate-security-advisory', 'reference', 'cvedata']

packages:
  - slug: wpewebkit
    name: "WPE WebKit"
  - slug: libwpe
    name: "libwpe"
  - slug: wpebackend-fdo
    name: "WPEBackend-fdo"
  - slug: cog
    name: "Cog"

release_dir: /releases

release_kinds:
  - tag: stable
    color: primary
  - tag: unstable
    color: secondary

# Build settings
markdown: kramdown
